name: sahra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_getit: ^3.0.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - .env
  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/Fira_Sans/FiraSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fira_Sans/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fira_Sans/FiraSans-BlackItalic.ttf
          weight: 900
          style: italic
