// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4hoYi3v_8itK9g1R-_9kuI3swKyFI7jI',
    appId: '1:771034140705:web:42bb91a4b281ae109a5360',
    messagingSenderId: '771034140705',
    projectId: 'sahra-aa78b',
    authDomain: 'sahra-aa78b.firebaseapp.com',
    storageBucket: 'sahra-aa78b.firebasestorage.app',
    measurementId: 'G-5HNCGR403L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkxwJbDyOPHp36C9w4_Wv6Fy6oozDYsk',
    appId: '1:771034140705:android:178019afbbd621ac9a5360',
    messagingSenderId: '771034140705',
    projectId: 'sahra-aa78b',
    storageBucket: 'sahra-aa78b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu8wSdk8fhieHs_mMCKJ56kJijhQ5pmFQ',
    appId: '1:771034140705:ios:79e0c3d07902b4309a5360',
    messagingSenderId: '771034140705',
    projectId: 'sahra-aa78b',
    storageBucket: 'sahra-aa78b.firebasestorage.app',
    iosBundleId: 'com.example.sahra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu8wSdk8fhieHs_mMCKJ56kJijhQ5pmFQ',
    appId: '1:771034140705:ios:79e0c3d07902b4309a5360',
    messagingSenderId: '771034140705',
    projectId: 'sahra-aa78b',
    storageBucket: 'sahra-aa78b.firebasestorage.app',
    iosBundleId: 'com.example.sahra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4hoYi3v_8itK9g1R-_9kuI3swKyFI7jI',
    appId: '1:771034140705:web:7c563ab557e37e6c9a5360',
    messagingSenderId: '771034140705',
    projectId: 'sahra-aa78b',
    authDomain: 'sahra-aa78b.firebaseapp.com',
    storageBucket: 'sahra-aa78b.firebasestorage.app',
    measurementId: 'G-2B4WCRYC1L',
  );
}
